AllCops:
  NewCops: enable
  Exclude:
    - "*/*_test.rb"

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/FrozenStringLiteralComment:
  Enabled: false

Style/MutableConstant:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Max: 20
Metrics/ParameterLists:
  Max: 50
Metrics/AbcSize:
  Max: 30

Style/GlobalVars:
  Enabled: false

Style/ClassVars:
  Enabled: false

Style/WordArray:
  EnforcedStyle: brackets
